name: Deploy FitFlavourz to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Replace Firebase configuration placeholders
        run: |
          # Escape secrets to prevent sed errors
          ESCAPED_API_KEY=$(printf '%s\n' "${{ secrets.FIREBASE_API_KEY }}" | sed 's/[&/\]/\\&/g')
          ESCAPED_AUTH_DOMAIN=$(printf '%s\n' "${{ secrets.FIREBASE_AUTH_DOMAIN }}" | sed 's/[&/\]/\\&/g')
          ESCAPED_DATABASE_URL=$(printf '%s\n' "${{ secrets.FIREBASE_DATABASE_URL }}" | sed 's/[&/\]/\\&/g')
          ESCAPED_PROJECT_ID=$(printf '%s\n' "${{ secrets.FIREBASE_PROJECT_ID }}" | sed 's/[&/\]/\\&/g')

          sed -i "s/FIREBASE_API_KEY_PLACEHOLDER/$ESCAPED_API_KEY/g" *.html
          sed -i "s/FIREBASE_AUTH_DOMAIN_PLACEHOLDER/$ESCAPED_AUTH_DOMAIN/g" *.html  
          sed -i "s/FIREBASE_DATABASE_URL_PLACEHOLDER/$ESCAPED_DATABASE_URL/g" *.html
          sed -i "s/FIREBASE_PROJECT_ID_PLACEHOLDER/$ESCAPED_PROJECT_ID/g" *.html

          echo "Secrets replaced successfully"
          grep -n "firebase" *.html || echo "No firebase config found to verify"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
