# .github/workflows/deploy.yml
name: Deploy FitFlavourz to GitHub Pages
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Replace Firebase configuration placeholders
        run: |
          echo "Current directory contents:"
          ls -la
          
          echo "Looking for HTML files..."
          find . -name "*.html" -type f
          
          # Check if HTML files exist and process them
          HTML_FILES=$(find . -name "*.html" -type f)
          if [ -n "$HTML_FILES" ]; then
            echo "Found HTML files to process"
            
            # Process each HTML file
            while IFS= read -r file; do
              if [ -f "$file" ]; then
                echo "Processing $file..."
                
                # Show current content for debugging (first few lines with Firebase config)
                echo "Current Firebase config in $file:"
                grep -n "FIREBASE.*PLACEHOLDER" "$file" || echo "No placeholders found in $file"
                
                # Replace placeholders with actual values from GitHub secrets
                sed -i "s/FIREBASE_API_KEY_PLACEHOLDER/${{ secrets.FIREBASE_API_KEY }}/g" "$file"
                sed -i "s/FIREBASE_AUTH_DOMAIN_PLACEHOLDER/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g" "$file"
                sed -i "s/FIREBASE_DATABASE_URL_PLACEHOLDER/${{ secrets.FIREBASE_DATABASE_URL }}/g" "$file"
                sed -i "s/FIREBASE_PROJECT_ID_PLACEHOLDER/${{ secrets.FIREBASE_PROJECT_ID }}/g" "$file"
                
                echo "Completed processing $file"
                
                # Verify replacements
                echo "Checking for remaining placeholders in $file:"
                grep -n "FIREBASE.*PLACEHOLDER" "$file" || echo "All placeholders replaced in $file"
              fi
            done <<< "$HTML_FILES"
            
          else
            echo "No HTML files found"
            echo "Repository structure:"
            find . -type f \( -name "*.html" -o -name "*.js" -o -name "*.css" \) | head -10
            exit 1
          fi
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
